import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/component/navbar/Navbar";
import Footer from "@/component/footer/Footer";
import { montserrat, poppins } from "../../public/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div
          className={`fixed top-7 left-0 w-full z-50  ${poppins.variable} ${montserrat.variable} `}
        >
          <Navbar />
        </div>
        <main className="bg-[#7E5AFF]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
